// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: programa/parserlexer/Lexer.jflex

package parserlexer;
import java_cup.runtime.*;

/*
 * Analizador Léxico para lenguaje de configuración de chips
 * Objetivo: Definir las reglas léxicas (expresiones regulares) que JFlex usará para generar la clase Lexer.java.
 *           Este archivo se encarga de reconocer todos los tokens válidos del lenguaje.
 * Entrada: Archivo de texto con código fuente en el lenguaje personalizado.
 * Salida: Tokens de tipo Symbol (definidos en sym.java) para cada lexema encontrado.
 * Restricciones: Requiere codificación UTF-8 para reconocer caracteres especiales como 'Σ', '¡', '¿', 'є', 'э'.
 */


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int PANIC_MODE = 4;
  public static final int MULTICOMMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\2\u0100\1\u0200\1\u0300\u10fb\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\4\1\5\2\0\1\6\1\0\1\7\2\0\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\11\17\1\0"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\32\26\1\27"+
    "\1\30\1\31\1\32\1\26\1\0\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\26\1\44"+
    "\1\45\1\26\1\46\1\47\1\50\1\26\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\2\26\1\0\1\60"+
    "\1\0\1\61\42\0\1\62\35\0\1\63\u01e3\0\1\64"+
    "\251\0\1\65\6\0\1\66\253\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\1\10\1\11\1\12\2\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\16\22"+
    "\1\2\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\2\37\3\40\1\41\1\0\1\42\1\43"+
    "\1\44\1\45\2\0\1\46\1\47\1\50\20\22\1\51"+
    "\6\22\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\6\22\1\61\3\22\1\62\1\63\1\22\1\64\11\22"+
    "\1\65\1\22\1\66\1\67\1\22\1\70\1\71\1\72"+
    "\2\22\1\73\1\22\1\74\2\22\1\75\1\22\1\76"+
    "\1\77\1\22\1\100\1\22\1\101\1\102\1\103\3\22"+
    "\1\104\1\105\1\22\1\106\1\107\1\110";

  private static int [] zzUnpackAction() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\334\0\u0113\0\334"+
    "\0\334\0\334\0\u014a\0\334\0\u0181\0\334\0\u01b8\0\u01ef"+
    "\0\u0226\0\u025d\0\334\0\u0294\0\u02cb\0\u0302\0\334\0\334"+
    "\0\u0339\0\334\0\334\0\334\0\u0370\0\u03a7\0\u03de\0\u0415"+
    "\0\u044c\0\u0483\0\u04ba\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd"+
    "\0\u0604\0\u063b\0\u0672\0\334\0\334\0\334\0\u06a9\0\334"+
    "\0\u06e0\0\334\0\u0717\0\u074e\0\334\0\u0785\0\u07bc\0\334"+
    "\0\u07f3\0\334\0\u082a\0\334\0\334\0\334\0\334\0\u0861"+
    "\0\u0226\0\334\0\334\0\334\0\u0898\0\u08cf\0\u0906\0\u093d"+
    "\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\u0af5"+
    "\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1\0\u0339\0\u0c08\0\u0c3f\0\u0c76"+
    "\0\u0cad\0\u0ce4\0\u0d1b\0\334\0\334\0\334\0\334\0\334"+
    "\0\334\0\u0861\0\u0d52\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65"+
    "\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41\0\u0339\0\u0339\0\u0f78\0\u0339"+
    "\0\u0faf\0\u0fe6\0\u101d\0\u1054\0\u108b\0\u10c2\0\u10f9\0\u1130"+
    "\0\u1167\0\u0339\0\u119e\0\u0339\0\u0339\0\u11d5\0\u0339\0\u0339"+
    "\0\u0339\0\u120c\0\u1243\0\u0339\0\u127a\0\u0339\0\u12b1\0\u12e8"+
    "\0\u0339\0\u131f\0\u0339\0\u0339\0\u1356\0\u0339\0\u138d\0\u0339"+
    "\0\u0339\0\u0339\0\u13c4\0\u13fb\0\u1432\0\u0339\0\u0339\0\u1469"+
    "\0\u0339\0\u0339\0\u0339";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\2\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\5\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\5"+
    "\1\33\1\34\1\31\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\31\1\43\1\31\1\44\1\45\1\46\1\31"+
    "\1\47\1\50\1\51\2\31\1\52\1\31\1\53\1\54"+
    "\1\55\1\56\1\57\1\5\1\60\2\61\2\0\1\61"+
    "\1\62\22\61\1\63\36\61\2\64\1\65\1\66\63\64"+
    "\2\67\1\70\1\71\61\67\1\72\1\67\71\0\1\6"+
    "\64\0\7\73\1\0\57\73\11\0\1\74\70\0\1\75"+
    "\7\0\1\76\60\0\1\77\65\0\1\100\1\0\2\101"+
    "\63\0\1\100\1\0\2\22\71\0\1\102\66\0\1\103"+
    "\66\0\1\104\62\0\2\31\6\0\1\31\4\0\25\31"+
    "\25\0\2\31\6\0\1\31\4\0\14\31\1\105\1\31"+
    "\1\106\6\31\25\0\2\31\6\0\1\31\4\0\7\31"+
    "\1\107\4\31\1\110\10\31\25\0\2\31\6\0\1\31"+
    "\4\0\4\31\1\111\20\31\25\0\2\31\6\0\1\31"+
    "\4\0\12\31\1\112\1\113\10\31\1\114\25\0\2\31"+
    "\6\0\1\31\4\0\1\115\11\31\1\116\1\31\1\117"+
    "\10\31\25\0\2\31\6\0\1\31\4\0\4\31\1\120"+
    "\3\31\1\121\14\31\25\0\2\31\6\0\1\31\4\0"+
    "\13\31\1\122\11\31\25\0\2\31\6\0\1\31\4\0"+
    "\14\31\1\123\10\31\25\0\2\31\6\0\1\31\4\0"+
    "\1\124\24\31\25\0\2\31\6\0\1\31\4\0\5\31"+
    "\1\125\17\31\25\0\2\31\6\0\1\31\4\0\4\31"+
    "\1\126\20\31\25\0\2\31\6\0\1\31\4\0\7\31"+
    "\1\127\10\31\1\130\4\31\25\0\2\31\6\0\1\31"+
    "\4\0\16\31\1\131\6\31\25\0\2\31\6\0\1\31"+
    "\4\0\7\31\1\132\4\31\1\133\10\31\7\0\2\53"+
    "\2\0\63\53\22\0\1\134\44\0\2\61\2\0\1\61"+
    "\1\0\22\61\1\0\36\61\5\0\1\135\40\0\1\136"+
    "\2\0\1\137\1\0\1\140\13\0\2\64\2\0\63\64"+
    "\2\0\1\65\64\0\2\67\2\0\61\67\1\0\1\67"+
    "\2\0\1\70\73\0\1\141\75\0\2\142\65\0\2\31"+
    "\6\0\1\31\4\0\14\31\1\143\10\31\25\0\2\31"+
    "\6\0\1\31\4\0\4\31\1\144\20\31\25\0\2\31"+
    "\6\0\1\31\4\0\1\145\24\31\25\0\2\31\6\0"+
    "\1\31\4\0\1\146\24\31\25\0\2\31\6\0\1\31"+
    "\4\0\2\31\1\147\22\31\25\0\2\31\6\0\1\31"+
    "\4\0\17\31\1\150\5\31\25\0\2\31\6\0\1\31"+
    "\4\0\3\31\1\151\21\31\25\0\2\31\6\0\1\31"+
    "\4\0\10\31\1\152\14\31\25\0\2\31\6\0\1\31"+
    "\4\0\12\31\1\153\12\31\25\0\2\31\6\0\1\31"+
    "\4\0\14\31\1\154\10\31\25\0\2\31\6\0\1\31"+
    "\4\0\16\31\1\155\6\31\25\0\2\31\6\0\1\31"+
    "\4\0\20\31\1\156\4\31\25\0\2\31\6\0\1\31"+
    "\4\0\5\31\1\157\17\31\25\0\2\31\6\0\1\31"+
    "\4\0\20\31\1\160\4\31\25\0\2\31\6\0\1\31"+
    "\4\0\2\31\1\161\11\31\1\162\10\31\25\0\2\31"+
    "\6\0\1\31\4\0\22\31\1\163\2\31\25\0\2\31"+
    "\6\0\1\31\4\0\20\31\1\164\4\31\25\0\2\31"+
    "\6\0\1\31\4\0\14\31\1\165\10\31\25\0\2\31"+
    "\6\0\1\31\4\0\16\31\1\166\6\31\25\0\2\31"+
    "\6\0\1\31\4\0\21\31\1\167\3\31\25\0\2\31"+
    "\6\0\1\31\4\0\4\31\1\170\20\31\25\0\2\31"+
    "\6\0\1\31\4\0\16\31\1\171\6\31\25\0\2\31"+
    "\6\0\1\31\4\0\12\31\1\172\12\31\25\0\2\31"+
    "\6\0\1\31\4\0\1\173\24\31\25\0\2\31\6\0"+
    "\1\31\4\0\16\31\1\174\6\31\25\0\2\31\6\0"+
    "\1\31\4\0\12\31\1\175\12\31\25\0\2\31\6\0"+
    "\1\31\4\0\10\31\1\176\14\31\25\0\2\31\6\0"+
    "\1\31\4\0\4\31\1\177\20\31\25\0\2\31\6\0"+
    "\1\31\4\0\12\31\1\200\12\31\25\0\2\31\6\0"+
    "\1\31\4\0\20\31\1\201\4\31\25\0\2\31\6\0"+
    "\1\31\4\0\17\31\1\202\5\31\25\0\2\31\6\0"+
    "\1\31\4\0\1\203\24\31\25\0\2\31\6\0\1\31"+
    "\4\0\20\31\1\204\4\31\25\0\2\31\6\0\1\31"+
    "\4\0\1\205\24\31\25\0\2\31\6\0\1\31\4\0"+
    "\15\31\1\206\7\31\25\0\2\31\6\0\1\31\4\0"+
    "\10\31\1\207\14\31\25\0\2\31\6\0\1\31\4\0"+
    "\21\31\1\210\3\31\25\0\2\31\6\0\1\31\4\0"+
    "\23\31\1\211\1\31\25\0\2\31\6\0\1\31\4\0"+
    "\10\31\1\212\14\31\25\0\2\31\6\0\1\31\4\0"+
    "\4\31\1\213\20\31\25\0\2\31\6\0\1\31\4\0"+
    "\13\31\1\214\11\31\25\0\2\31\6\0\1\31\4\0"+
    "\12\31\1\215\12\31\25\0\2\31\6\0\1\31\4\0"+
    "\11\31\1\216\13\31\25\0\2\31\6\0\1\31\4\0"+
    "\3\31\1\217\21\31\25\0\2\31\6\0\1\31\4\0"+
    "\4\31\1\220\20\31\25\0\2\31\6\0\1\31\4\0"+
    "\20\31\1\221\4\31\25\0\2\31\6\0\1\31\4\0"+
    "\12\31\1\222\12\31\25\0\2\31\6\0\1\31\4\0"+
    "\3\31\1\223\21\31\25\0\2\31\6\0\1\31\4\0"+
    "\16\31\1\224\6\31\25\0\2\31\6\0\1\31\4\0"+
    "\13\31\1\225\11\31\25\0\2\31\6\0\1\31\4\0"+
    "\3\31\1\226\21\31\25\0\2\31\6\0\1\31\4\0"+
    "\4\31\1\227\20\31\25\0\2\31\6\0\1\31\4\0"+
    "\1\230\24\31\25\0\2\31\6\0\1\31\4\0\13\31"+
    "\1\231\11\31\25\0\2\31\6\0\1\31\4\0\6\31"+
    "\1\232\16\31\25\0\2\31\6\0\1\31\4\0\3\31"+
    "\1\233\21\31\7\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5280];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\2\11\1\1\3\11\1\1\1\11\1\1\1\11"+
    "\4\1\1\11\3\1\2\11\1\1\3\11\17\1\3\11"+
    "\1\1\1\11\1\1\1\11\2\1\1\11\2\1\1\11"+
    "\1\1\1\11\1\0\4\11\2\0\3\11\27\1\6\11"+
    "\72\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  // Buffer para ir construyendo strings literales caracter por caracter cuando estamos en el estado STRING
  StringBuffer string = new StringBuffer();

  /*
   * Método symbol (sin valor)
   * Objetivo: Crear un objeto Symbol para tokens simples (palabras reservadas, operadores).
   * Entrada: type (ID numérico del token).
   * Salida: Objeto Symbol con la línea y columna ajustadas (base 1 para lectura humana).
   */
  private Symbol symbol(int type) {
    return new Symbol(type, yyline + 1, yycolumn + 1);
  }
  
  /*
   * Método symbol (con valor)
   * Objetivo: Crear un objeto Symbol para tokens complejos que llevan datos asociados (literales, IDs).
   * Entrada: type (ID numérico del token), value (valor del lexema parseado).
   * Salida: Objeto Symbol con tipo, valor, línea y columna.
   */
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline + 1, yycolumn + 1, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case MULTICOMMENT: {
              yybegin(YYINITIAL);
        return symbol(sym.ERROR, "Comentario multilinea no cerrado");
            }  // fall though
            case 156: break;
            default:
          { return new java_cup.runtime.Symbol(sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { String elementoDesconocido = yytext();
    System.err.println("Error: Elemento desconocido <" + elementoDesconocido + 
                       "> en la línea " + (yyline + 1));
    yybegin(PANIC_MODE); 
    return symbol(sym.ERROR, elementoDesconocido);
            }
          // fall through
          case 73: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 74: break;
          case 3:
            { return symbol(sym.CLOSE_BLOCK);
            }
          // fall through
          case 75: break;
          case 4:
            { string.setLength(0); 
                        string.append('\"'); 
                        yybegin(STRING);
            }
          // fall through
          case 76: break;
          case 5:
            { return symbol(sym.MOD);
            }
          // fall through
          case 77: break;
          case 6:
            { return symbol(sym.MULT);
            }
          // fall through
          case 78: break;
          case 7:
            { return symbol(sym.PLUS);
            }
          // fall through
          case 79: break;
          case 8:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 80: break;
          case 9:
            { return symbol(sym.MINUS);
            }
          // fall through
          case 81: break;
          case 10:
            { return symbol(sym.DIV);
            }
          // fall through
          case 82: break;
          case 11:
            { return symbol(sym.INT_LITERAL, (yytext()));
            }
          // fall through
          case 83: break;
          case 12:
            { return symbol(sym.SEMICOLON);
            }
          // fall through
          case 84: break;
          case 13:
            { return symbol(sym.LT);
            }
          // fall through
          case 85: break;
          case 14:
            { return symbol(sym.ASSIGN);
            }
          // fall through
          case 86: break;
          case 15:
            { return symbol(sym.GT);
            }
          // fall through
          case 87: break;
          case 16:
            { return symbol(sym.CLOSE_PAREN);
            }
          // fall through
          case 88: break;
          case 17:
            { return symbol(sym.AND);
            }
          // fall through
          case 89: break;
          case 18:
            { return symbol(sym.ID, yytext());
            }
          // fall through
          case 90: break;
          case 19:
            { return symbol(sym.OPEN_BRACKET);
            }
          // fall through
          case 91: break;
          case 20:
            { return symbol(sym.CLOSE_BRACKET);
            }
          // fall through
          case 92: break;
          case 21:
            { return symbol(sym.POWER);
            }
          // fall through
          case 93: break;
          case 22:
            { return symbol(sym.OR);
            }
          // fall through
          case 94: break;
          case 23:
            { return symbol(sym.OPEN_BLOCK);
            }
          // fall through
          case 95: break;
          case 24:
            { return symbol(sym.OPEN_PAREN);
            }
          // fall through
          case 96: break;
          case 25:
            { return symbol(sym.NOT);
            }
          // fall through
          case 97: break;
          case 26:
            { yybegin(MULTICOMMENT);
            }
          // fall through
          case 98: break;
          case 27:
            { string.append(yytext());
            }
          // fall through
          case 99: break;
          case 28:
            { string.append('\"'); 
                                     yybegin(YYINITIAL); 
                                     return symbol(sym.STRING_LITERAL, 
                                                   string.toString());
            }
          // fall through
          case 100: break;
          case 29:
            { string.append('\\');
            }
          // fall through
          case 101: break;
          case 30:
            { /* consumir basura de la línea actual */
            }
          // fall through
          case 102: break;
          case 31:
            { yybegin(YYINITIAL); /* al cambiar de línea, reiniciar */
            }
          // fall through
          case 103: break;
          case 32:
            { /* ignorar */
            }
          // fall through
          case 104: break;
          case 33:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 105: break;
          case 34:
            { return symbol(sym.INCREMENT);
            }
          // fall through
          case 106: break;
          case 35:
            { return symbol(sym.DECREMENT);
            }
          // fall through
          case 107: break;
          case 36:
            { return symbol(sym.ARROW);
            }
          // fall through
          case 108: break;
          case 37:
            { return symbol(sym.INT_DIV);
            }
          // fall through
          case 109: break;
          case 38:
            { return symbol(sym.LTEQ);
            }
          // fall through
          case 110: break;
          case 39:
            { return symbol(sym.EQEQ);
            }
          // fall through
          case 111: break;
          case 40:
            { return symbol(sym.GTEQ);
            }
          // fall through
          case 112: break;
          case 41:
            { return symbol(sym.OF);
            }
          // fall through
          case 113: break;
          case 42:
            { return symbol(sym.NEQ);
            }
          // fall through
          case 114: break;
          case 43:
            { string.append('\"');
            }
          // fall through
          case 115: break;
          case 44:
            { string.append('\n');
            }
          // fall through
          case 116: break;
          case 45:
            { string.append('\r');
            }
          // fall through
          case 117: break;
          case 46:
            { string.append('\t');
            }
          // fall through
          case 118: break;
          case 47:
            { return symbol(sym.CHAR_LITERAL, 
                               yytext());
            }
          // fall through
          case 119: break;
          case 48:
            { return symbol(sym.FLOAT_LITERAL, (yytext()));
            }
          // fall through
          case 120: break;
          case 49:
            { return symbol(sym.END);
            }
          // fall through
          case 121: break;
          case 50:
            { return symbol(sym.FOR);
            }
          // fall through
          case 122: break;
          case 51:
            { return symbol(sym.GET);
            }
          // fall through
          case 123: break;
          case 52:
            { return symbol(sym.INT);
            }
          // fall through
          case 124: break;
          case 53:
            { return symbol(sym.BOOL);
            }
          // fall through
          case 125: break;
          case 54:
            { return symbol(sym.CHAR);
            }
          // fall through
          case 126: break;
          case 55:
            { return symbol(sym.COAL);
            }
          // fall through
          case 127: break;
          case 56:
            { return symbol(sym.ELSE);
            }
          // fall through
          case 128: break;
          case 57:
            { return symbol(sym.ENDL);
            }
          // fall through
          case 129: break;
          case 58:
            { return symbol(sym.EXIT);
            }
          // fall through
          case 130: break;
          case 59:
            { return symbol(sym.GIFT);
            }
          // fall through
          case 131: break;
          case 60:
            { return symbol(sym.LOOP);
            }
          // fall through
          case 132: break;
          case 61:
            { return symbol(sym.SHOW);
            }
          // fall through
          case 133: break;
          case 62:
            { return symbol(sym.TRUE);
            }
          // fall through
          case 134: break;
          case 63:
            { return symbol(sym.WHEN);
            }
          // fall through
          case 135: break;
          case 64:
            { return symbol(sym.BREAK);
            }
          // fall through
          case 136: break;
          case 65:
            { return symbol(sym.FALSE);
            }
          // fall through
          case 137: break;
          case 66:
            { return symbol(sym.FLOAT);
            }
          // fall through
          case 138: break;
          case 67:
            { return symbol(sym.LOCAL);
            }
          // fall through
          case 139: break;
          case 68:
            { return symbol(sym.WORLD);
            }
          // fall through
          case 140: break;
          case 69:
            { return symbol(sym.DECIDE);
            }
          // fall through
          case 141: break;
          case 70:
            { return symbol(sym.RETURN);
            }
          // fall through
          case 142: break;
          case 71:
            { return symbol(sym.STRING);
            }
          // fall through
          case 143: break;
          case 72:
            { return symbol(sym.NAVIDAD);
            }
          // fall through
          case 144: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
