
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parserlexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHEN = 18;
  public static final int SHOW = 22;
  public static final int STRING_LITERAL = 57;
  public static final int GTEQ = 43;
  public static final int OPEN_PAREN = 29;
  public static final int POWER = 41;
  public static final int MULT = 37;
  public static final int INCREMENT = 33;
  public static final int CHAR = 7;
  public static final int CHAR_LITERAL = 58;
  public static final int LTEQ = 42;
  public static final int INT = 4;
  public static final int MINUS = 36;
  public static final int FOR = 19;
  public static final int DECREMENT = 34;
  public static final int SEMICOLON = 54;
  public static final int NOT = 50;
  public static final int AND = 48;
  public static final int ENDL = 24;
  public static final int LT = 46;
  public static final int DECIDE = 12;
  public static final int CLOSE_PAREN = 30;
  public static final int COAL = 10;
  public static final int OR = 49;
  public static final int COMMA = 53;
  public static final int BOOL = 6;
  public static final int GET = 23;
  public static final int NAVIDAD = 9;
  public static final int DIV = 38;
  public static final int PLUS = 35;
  public static final int OPEN_BLOCK = 27;
  public static final int LOOP = 16;
  public static final int EXIT = 17;
  public static final int ASSIGN = 51;
  public static final int ID = 59;
  public static final int OF = 13;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int TRUE = 25;
  public static final int error = 1;
  public static final int EQEQ = 44;
  public static final int MOD = 40;
  public static final int NEQ = 45;
  public static final int CLOSE_BRACKET = 32;
  public static final int BREAK = 21;
  public static final int OPEN_BRACKET = 31;
  public static final int WORLD = 2;
  public static final int ARROW = 52;
  public static final int ELSE = 14;
  public static final int CLOSE_BLOCK = 28;
  public static final int FLOAT = 5;
  public static final int END = 15;
  public static final int INT_DIV = 39;
  public static final int STRING = 8;
  public static final int LOCAL = 3;
  public static final int FLOAT_LITERAL = 56;
  public static final int FALSE = 26;
  public static final int GT = 47;
  public static final int GIFT = 11;
  public static final int INT_LITERAL = 55;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "WORLD",
  "LOCAL",
  "INT",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "NAVIDAD",
  "COAL",
  "GIFT",
  "DECIDE",
  "OF",
  "ELSE",
  "END",
  "LOOP",
  "EXIT",
  "WHEN",
  "FOR",
  "RETURN",
  "BREAK",
  "SHOW",
  "GET",
  "ENDL",
  "TRUE",
  "FALSE",
  "OPEN_BLOCK",
  "CLOSE_BLOCK",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "INCREMENT",
  "DECREMENT",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "INT_DIV",
  "MOD",
  "POWER",
  "LTEQ",
  "GTEQ",
  "EQEQ",
  "NEQ",
  "LT",
  "GT",
  "AND",
  "OR",
  "NOT",
  "ASSIGN",
  "ARROW",
  "COMMA",
  "SEMICOLON",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "ID"
  };
}

